/**
 * Shared templates used by both the MCP server tools and the CLI.
 * Everything here is plain text generation, no external dependencies.
 */

export type ScriptKind = "Script" | "LocalScript" | "ModuleScript";

export function scriptBoilerplate(kind: ScriptKind, scriptName: string): string {
	const header = `--!strict
--[[
	${scriptName} (${kind})
	Generated by StudioPilot.
]]
`;
	if (kind === "ModuleScript") {
		return `${header}
local ${scriptName} = {}

function ${scriptName}.Init()
	-- TODO: initialize module
end

return ${scriptName}
`;
	}
	if (kind === "LocalScript") {
		return `${header}
local Players = game:GetService("Players")
local player = Players.LocalPlayer

-- TODO: client logic here
`;
	}
	return `${header}
local Players = game:GetService("Players")

-- TODO: server logic here
`;
}

export function rojoProjectJson(projectName: string): string {
	return JSON.stringify(
		{
			name: projectName,
			tree: {
				$className: "DataModel",
				ReplicatedStorage: {
					$className: "ReplicatedStorage",
					Shared: {
						$path: "src/shared",
					},
				},
				ServerScriptService: {
					$className: "ServerScriptService",
					Server: {
						$path: "src/server",
					},
				},
				StarterPlayer: {
					$className: "StarterPlayer",
					StarterPlayerScripts: {
						$className: "StarterPlayerScripts",
						Client: {
							$path: "src/client",
						},
					},
				},
			},
		},
		null,
		"\t"
	);
}

export function agentsMd(projectName: string): string {
	return `# AGENTS.md - ${projectName}

This project was scaffolded with StudioPilot for AI-assisted Roblox development.

## Project layout (Rojo)

- \`src/server/\` - server-side Scripts. Runs on the server only.
- \`src/client/\` - LocalScripts. Runs on each client only.
- \`src/shared/\` - ModuleScripts shared between server and client (via ReplicatedStorage).

## Rules for AI agents working in this repo

1. **Respect the client/server boundary.** Never call server-only APIs from
   \`src/client\`, and never put LocalScripts in server containers.
2. **Use \`--!strict\` mode** at the top of every Luau file.
3. **Get services with \`game:GetService()\`**, never with dot indexing
   (e.g. \`game:GetService("Players")\`, not \`game.Players\`).
4. **Cross-boundary communication** goes through RemoteEvents/RemoteFunctions
   placed in ReplicatedStorage. Validate all client input on the server.
5. **Run \`studiopilot validate\` logic** (the \`validate_project\` MCP tool)
   after structural changes, and keep \`project.json\` in sync with the
   folder layout.

## Useful commands

- \`rojo serve\` - serve the project to Roblox Studio via the Rojo plugin
- \`rojo build -o game.rbxlx\` - build a place file
- \`stylua src/\` - format Luau code
`;
}

export function projectReadme(projectName: string): string {
	return `# ${projectName}

A Roblox game project scaffolded with [StudioPilot](https://github.com/kkcblegit8-ship-it/StudioPilot).

## Layout

- \`src/server/\` - server Scripts
- \`src/client/\` - client LocalScripts
- \`src/shared/\` - shared ModuleScripts (replicated)

## Development

1. Install the [Rojo](https://rojo.space/) Studio plugin.
2. Run \`rojo serve\` in this directory.
3. Connect from Studio and start building.
`;
}

export const GITIGNORE = `/build
*.rbxlx
*.rbxl
`;

export const MCP_CONFIG_JSON = JSON.stringify(
	{
		mcpServers: {
			studiopilot: {
				command: "npx",
				args: ["-y", "studiopilot-mcp"],
			},
		},
	},
	null,
	"\t"
);
